# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ac19b05e1db53d196cfc09d90843e274b9b23787cebeb85430c090e5568db3fb1faf7e23a5819b0cfe5750dfd6766ac8ac7d9cfac4ab78f7d1dd6bb2a676416

test:
  secret_key_base: fa92858ae581a9b5e13d13315cb63cf10ba4a30d3752bdc38aa8fe69091b3b56897b77dd6e8c1264a2ecd29e91b8fd8a2cc0835c021d72db84f09feacbb5b03b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
