# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b65c897e9359ec03a802a5ea9683bc6f5555240d69f70a5064d6e8aa9f67d61ac81a22f307ae7e5f4930349d616ac9d5d5e018b9cc8dd2471866467044ff698b

test:
  secret_key_base: 40d62703a7c88bab7f80403c7866638a6f267515784aa02fc9b3c2bdc925f256d3006a4f8454e3c3d1aea79496185eb9649bcc75d8013ffa2341b86f21aaf444

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
